version: '2.0'
networks:
  main:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
services:

  hdfs-master:
    image: hdfs:latest
    ports:
     - "50070:50070"
     - "8088:8088"
    networks:
     - main
    command: master
    container_name: hadoop-master

  hdfs-worker-1:
    image: hdfs:latest
    command: worker
    ports:
     - "50075"
     - "8142:8042"
     - "19888:19888"
    networks:
     - main
    links:
     - hdfs-master
    container_name: hadoop-worker-1


  kafka-broker-1:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
    ports:
      - 9092:9092
    networks:
     - main
    container_name: broker1
    links:
      - zookeeper

  kafka-broker-2:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_BROKER_ID: 2
    ports:
      - 9093:9092
    networks:
     - main
    container_name: broker2
    links:
      - zookeeper

  kafka-broker-3:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_BROKER_ID: 3
    ports:
      - 9094:9092
    networks:
     - main
    container_name: broker3
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    networks:
     - main
    container_name: zookeeper

  cassandra_1:
    image: cassandra:3.11.1
    ports:
      - 7000:7000
      - 9042:9042
    networks:
     - main
    container_name: cassandra1
    links:
      - cassandra_2

  cassandra_2:
    image: cassandra:3.11.1
    ports:
      - 7070:7000
    networks:
     - main
    container_name: cassandra2

  connect:
    image: confluentinc/cp-kafka-connect:3.3.0
    volumes:
      - ./hdfs-connector.properties:/opt/config/connect/hdfs-connector.properties
      - ./connect-distributed.properties:/opt/config/connect/connect-distributed.properties
    command: connect-distributed /opt/config/connect/connect-distributed.properties
    ports:
      - 8083:8083
    networks:
     - main
    container_name: connect
    links:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

