version: '2.0'
networks:
  main:
    driver: bridge
services:

  hdfs-master:
    image: hdfs:latest
    networks:
      - main
    ports:
     - "50070:50070"
     - "8088:8088"
    command: master
    hostname: hadoop-master

  hdfs-worker-1:
    image: hdfs:latest
    command: worker
    networks:
      - main
    ports:
     - "50075"
     - "8142:8042"
     - "19888:19888"

  kafka-broker-1:
    image: confluent/kafka
    networks:
      - main
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
    ports:
      - 9092:9092
    links:
      - zookeeper

  kafka-broker-2:
    image: confluent/kafka
    networks:
      - main
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_BROKER_ID: 2
    ports:
      - 9093:9092
    links:
      - zookeeper

  kafka-broker-3:
    image: confluent/kafka
    networks:
      - main
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_BROKER_ID: 3
    ports:
      - 9094:9092
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5
    networks:
      - main
    ports:
      - 2181:2181

  connect:
    image: confluentinc/cp-kafka-connect:3.3.0
    networks:
      - main
    volumes:
      - ./hdfs-connector.properties:/opt/config/connect/hdfs-connector.properties
      - ./connect-distributed.properties:/opt/config/connect/connect-distributed.properties
    command: connect-distributed /opt/config/connect/connect-distributed.properties
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

