version: '2.0'
services:

  kafka-broker-1:
    image: confluent/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
    ports:
      - 9092:9092
    links:
      - zookeeper

  kafka-broker-2:
    image: confluent/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_BROKER_ID: 2
    ports:
      - 9093:9092
    links:
      - zookeeper

  kafka-broker-3:
    image: confluent/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_BROKER_ID: 3
    ports:
      - 9094:9092
    links:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181

  connect:
    image: confluentinc/cp-kafka-connect:3.3.0
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-1:9092
      CONNECT_GROUP_ID: connect
      CONNECT_CONFIG_STORAGE_TOPIC: config-topic
      CONNECT_OFFSET_STORAGE_TOPIC: offset-topic
      CONNECT_STATUS_STORAGE_TOPIC: status-topic
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

